/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeServicoRouteImport } from './routes/termos-de-servico'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as MiniBikeErgometricaRouteImport } from './routes/mini-bike-ergometrica'
import { Route as MercadoLivreFullRouteImport } from './routes/mercado-livre-full'
import { Route as BicicletaErgometricaSpinningRouteImport } from './routes/bicicleta-ergometrica-spinning'
import { Route as IndexRouteImport } from './routes/index'

const TermosDeServicoRoute = TermosDeServicoRouteImport.update({
  id: '/termos-de-servico',
  path: '/termos-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MiniBikeErgometricaRoute = MiniBikeErgometricaRouteImport.update({
  id: '/mini-bike-ergometrica',
  path: '/mini-bike-ergometrica',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoLivreFullRoute = MercadoLivreFullRouteImport.update({
  id: '/mercado-livre-full',
  path: '/mercado-livre-full',
  getParentRoute: () => rootRouteImport,
} as any)
const BicicletaErgometricaSpinningRoute =
  BicicletaErgometricaSpinningRouteImport.update({
    id: '/bicicleta-ergometrica-spinning',
    path: '/bicicleta-ergometrica-spinning',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bicicleta-ergometrica-spinning': typeof BicicletaErgometricaSpinningRoute
  '/mercado-livre-full': typeof MercadoLivreFullRoute
  '/mini-bike-ergometrica': typeof MiniBikeErgometricaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bicicleta-ergometrica-spinning': typeof BicicletaErgometricaSpinningRoute
  '/mercado-livre-full': typeof MercadoLivreFullRoute
  '/mini-bike-ergometrica': typeof MiniBikeErgometricaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bicicleta-ergometrica-spinning': typeof BicicletaErgometricaSpinningRoute
  '/mercado-livre-full': typeof MercadoLivreFullRoute
  '/mini-bike-ergometrica': typeof MiniBikeErgometricaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bicicleta-ergometrica-spinning'
    | '/mercado-livre-full'
    | '/mini-bike-ergometrica'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/termos-de-servico'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bicicleta-ergometrica-spinning'
    | '/mercado-livre-full'
    | '/mini-bike-ergometrica'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/termos-de-servico'
  id:
    | '__root__'
    | '/'
    | '/bicicleta-ergometrica-spinning'
    | '/mercado-livre-full'
    | '/mini-bike-ergometrica'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/termos-de-servico'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BicicletaErgometricaSpinningRoute: typeof BicicletaErgometricaSpinningRoute
  MercadoLivreFullRoute: typeof MercadoLivreFullRoute
  MiniBikeErgometricaRoute: typeof MiniBikeErgometricaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosDeServicoRoute: typeof TermosDeServicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-servico': {
      id: '/termos-de-servico'
      path: '/termos-de-servico'
      fullPath: '/termos-de-servico'
      preLoaderRoute: typeof TermosDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mini-bike-ergometrica': {
      id: '/mini-bike-ergometrica'
      path: '/mini-bike-ergometrica'
      fullPath: '/mini-bike-ergometrica'
      preLoaderRoute: typeof MiniBikeErgometricaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado-livre-full': {
      id: '/mercado-livre-full'
      path: '/mercado-livre-full'
      fullPath: '/mercado-livre-full'
      preLoaderRoute: typeof MercadoLivreFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bicicleta-ergometrica-spinning': {
      id: '/bicicleta-ergometrica-spinning'
      path: '/bicicleta-ergometrica-spinning'
      fullPath: '/bicicleta-ergometrica-spinning'
      preLoaderRoute: typeof BicicletaErgometricaSpinningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BicicletaErgometricaSpinningRoute: BicicletaErgometricaSpinningRoute,
  MercadoLivreFullRoute: MercadoLivreFullRoute,
  MiniBikeErgometricaRoute: MiniBikeErgometricaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosDeServicoRoute: TermosDeServicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
